name: Daily Attendance Automation

on:
  schedule:
    - cron: "30 2 * * *"  # Runs at 10:00 AM IST (2:30 AM UTC)
    - cron: "00 14 * * *" # Runs at 7:30 PM IST (14:00 UTC)
  workflow_dispatch: # Allows manual triggering of workflow

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install selenium webdriver-manager

      - name: Run Check-In Script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python checkin.py

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install selenium webdriver-manager

      - name: Run Check-Out Script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python checkout.py
