name: Daily Attendance Automation

on:
  schedule:
    - cron: "50 4 * * 1-5"  # Check-in at 10:20 AM IST (4:50 AM UTC)
    - cron: "50 13 * * 1-5" # Check-out at 7:00 PM IST (1:30 PM UTC)
  workflow_dispatch:
    inputs:
      action_type:
        description: 'Choose action (checkin or checkout)'
        required: true
        default: 'checkin'

jobs:
  checkin:
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action_type == 'checkin')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install selenium webdriver-manager

      - name: Run Check-In Script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python checkin.py

  checkout:
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action_type == 'checkout')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install selenium webdriver-manager

      - name: Run Check-Out Script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python checkout.py
